#!/usr/bin/env python3
"""Print signal-based bias-risk explanations from generated artifacts."""

from __future__ import annotations

import argparse
import csv
import textwrap
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Show representative bias-risk explanations.")
    parser.add_argument(
        "--explanations",
        default="results/v2/rule_explanations/ours_predicted_condition/explanations.csv",
        help="Path to explanations.csv generated by generate_rule_based_explanations.py.",
    )
    parser.add_argument("--uid", help="Optional exact UID such as Disability_status::544.")
    parser.add_argument("--seed", type=int, help="Optional seed filter.")
    parser.add_argument(
        "--risk-level",
        default="high",
        choices=["high", "moderate", "low", "utility_risk", "none", "any"],
        help="Bias-risk level to display when --uid is not supplied.",
    )
    parser.add_argument("--limit", type=int, default=5)
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def keep_row(row: dict[str, Any], args: argparse.Namespace) -> bool:
    if args.uid and row.get("uid") != args.uid:
        return False
    if args.seed is not None:
        try:
            if int(row.get("seed") or -1) != args.seed:
                return False
        except ValueError:
            return False
    if not args.uid and args.risk_level != "any" and row.get("bias_risk_level") != args.risk_level:
        return False
    return True


def print_case(row: dict[str, Any], width: int = 92) -> None:
    title = (
        f"{row.get('uid')} seed={row.get('seed')} "
        f"risk={row.get('bias_risk_level')} decision={row.get('decision_type')}"
    )
    print("=" * min(len(title), width))
    print(title)
    print("-" * min(len(title), width))
    print(f"condition: gold={row.get('context_condition')} predicted={row.get('predicted_condition')}")
    print(f"raw:   {row.get('primary_text')} ({row.get('raw_bias_direction')})")
    print(f"final: {row.get('final_text')} ({row.get('final_bias_direction')})")
    print(f"flags: {row.get('signal_flags') or 'none'}")
    print()
    print("Bias-risk explanation:")
    print(textwrap.fill(row.get("bias_risk_explanation") or "", width=width))
    print()
    print("Runtime explanation:")
    print(textwrap.fill(row.get("runtime_explanation") or "", width=width))
    print()


def main() -> int:
    args = parse_args()
    rows = load_rows(Path(args.explanations))
    selected = [row for row in rows if keep_row(row, args)]
    for row in selected[: args.limit]:
        print_case(row)
    if not selected:
        print("No matching explanation rows found.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
